spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888


#spring.application.name=config-server
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:/configurations
#server.port=8888
