spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service


#spring.config.import=optional:configserver:http://localhost:8888
#spring.application.name=discovery-service