spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/customer?authSource=admin
#      username: root
#      password: 123456
#      host: localhost
#      port: 27017
#      database: customer
#      authentication-database: admin
server:
  port: 8090